# Generated by Django 4.2.7 on 2023-11-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='BokkingDate',
            new_name='BookingDate',
        ),
    ]
